name: Build WPF App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
    
    # Альтернативный способ установки .NET Framework
    - name: Setup .NET Framework 4.6.1
      run: |
        # Используем chocolatey для установки
        choco install netfx-4.6.1-devpack -y
    
    - name: Restore NuGet packages
      run: nuget restore "DefineOverlayTree.sln"
    
    - name: Build solution
      run: msbuild "DefineOverlayTree.sln" /p:Configuration=Release /p:Platform="Any CPU"
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: WPF-App-Release
        path: |
          **/bin/Release/**/*
